balancer:
  image: jjperezaguinaga/balancer
  restart: always
  ports:
    - "80:80"
  links:
    - index:index
    - articles:articles

index:
  image: jjperezaguinaga/webpage
  restart: always
  ports:
    - "8080"

articles:
  image: jjperezaguinaga/articles
  restart: always
  ports:
    - "8080"
